config/routes.rb
Rails.application.routes.draw do
  root 'sessions#home'

  get 'load_planning' => 'loads#index'
  get 'orders_delivery' => 'orders_delivery#index'
  get 'get_delivery_data' => 'orders_delivery#get_delivery_data'
  get 'download_routing_list' => 'orders_delivery#download_routing_list'

  resources :order_releases

  post 'save_orders' => 'order_releases#save_orders'

  get 'get_available_orders' => 'loads#get_available_orders'
  get 'get_load_data' => 'loads#get_load_data'
  post 'submit_orders' => 'loads#submit_orders'
  post 'return_orders' => 'loads#return_orders'
  post 'reorder_planning_orders' => 'loads#reorder_planning_orders'
  post 'complete_load' => 'loads#complete_load'
  post 'split_order' => 'loads#split_order'
  post 'update_load_data' => 'loads#update_load_data'
  post 'reopen_load' => 'loads#reopen_load'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'

  match "*path", :to => "application#catch_routing_error", :via => :all

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>

    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <%= link_to "Larkin LLC", root_path, id: "logo" %>
      </div>

      <div class="col-sm-4">
        <% if logged_in? && can?(:order_management, OrderRelease) %>
            <ul class="tab nav navbar-nav navbar-right">
              <li><%= link_to "Order Management", order_releases_path %></li>
              <li><%= link_to "Load Planning", load_planning_path %></li>
            </ul>
        <% end %>
      </div>
      <div class="col-sm-5">
        <% if logged_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Logout from "+ current_user.login, logout_path, method: :delete %></li>
            </ul>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container-fluid">
  <% flash.each do |message_type, message|
     if message_type=='success' || message_type=='danger'%>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
     <% end %>
  <% end %>
  <%= yield %>
</div>
</body>
</html>